### ISSUE TITLE
Optical Flows

### ISSUE THREAD

**Issue by AMontiB** [ShujinW/Deep-Video-Inpainting-Localization#5]
Good Morning, 

I would like to ask if the optical flows have to be .flo or .png. 

Could you also provide additional information on how you organized the dataset (i.e. xxx/png/*png or xxx/png/yyy/*.png where yyy are N sub-directories)?

Regards, 
Andrea

**Comment by ShujinW** [comment]
Hello, 

The code I wrote requires the optical flow file to be in .flo format because it needs to handle both positive and negative values of floating point numbers.

The relationship between the path of the video frame and the path of its corresponding mask:  
mask_path = img_path.replace(‘png’, ‘msk’, 1)
